import type { QuoteCalculationInput } from "@/lib/quotes/calculate";

export const SAMPLE_SELLER = "Sudarshan Precision Works";
export const SAMPLE_CUSTOMER = "Asha Engineering Works";

export const SAMPLE_QUOTE_FIXTURES = {
  INR: {
    currency_code: "INR",
    tax_mode: "exclusive",
    discount_bps: 1200,
    charges: [],
    items: [
      {
        position: 1,
        product_id: "sample-coupling",
        sku_snapshot: "CPA-200",
        description_snapshot: "Precision coupling assembly",
        unit_code_snapshot: "EA",
        quantity_precision_snapshot: 0,
        unit_price_minor_snapshot: 1120000,
        currency_code: "INR",
        quantity_scaled: 2,
        quantity_scale: 1,
        tax_code_snapshot: "GST",
        tax_bps_snapshot: 1800,
        tax_price_basis_snapshot: "exclusive",
        tax_treatment_snapshot: "standard",
      },
      {
        position: 2,
        product_id: "sample-rail",
        sku_snapshot: "SFR-03",
        description_snapshot: "Stainless feed rail",
        unit_code_snapshot: "M",
        quantity_precision_snapshot: 3,
        unit_price_minor_snapshot: 390000,
        currency_code: "INR",
        quantity_scaled: 3000,
        quantity_scale: 1000,
        tax_code_snapshot: "GST",
        tax_bps_snapshot: 1800,
        tax_price_basis_snapshot: "exclusive",
        tax_treatment_snapshot: "standard",
      },
    ],
  },
  USD: {
    currency_code: "USD",
    tax_mode: "exclusive",
    discount_bps: 750,
    charges: [],
    items: [
      {
        position: 1,
        product_id: "sample-control",
        sku_snapshot: "CTRL-40",
        description_snapshot: "Control enclosure assembly",
        unit_code_snapshot: "EA",
        quantity_precision_snapshot: 0,
        unit_price_minor_snapshot: 184500,
        currency_code: "USD",
        quantity_scaled: 2,
        quantity_scale: 1,
        tax_code_snapshot: "SALES",
        tax_bps_snapshot: 825,
        tax_price_basis_snapshot: "exclusive",
        tax_treatment_snapshot: "standard",
      },
      {
        position: 2,
        product_id: "sample-cable",
        sku_snapshot: "CBL-08",
        description_snapshot: "Shielded installation cable",
        unit_code_snapshot: "M",
        quantity_precision_snapshot: 3,
        unit_price_minor_snapshot: 1825,
        currency_code: "USD",
        quantity_scaled: 12000,
        quantity_scale: 1000,
        tax_code_snapshot: "SALES",
        tax_bps_snapshot: 825,
        tax_price_basis_snapshot: "exclusive",
        tax_treatment_snapshot: "standard",
      },
    ],
  },
} as const satisfies Record<"INR" | "USD", QuoteCalculationInput>;
